spring:
  security:
    oauth2:
      resourceserver: # KeyCloak | localhost:8080 | Realm: posts-realm with public key
        jwt:
          issuer-uri: http://<YOUR_KEYCLOAK_URL>:<PORT>/realms/posts-realm

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery:8761/eureka/}

    instance:
      preferIpAddress: false
      hostname: ${spring.application.name}